### ISSUE TITLE
Picture uploads sometimes causing ThreadAbortException and request timeout

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Codespilot/vocadb#144]
```
Stack trace (IP and UA removed)

2013-09-26 18:51:55.1469 [] FATAL Exception for 'IP' [IP], URL POST 
'/Artist/EditBasicDetails', UA 'Chrome', referrer 
'http://vocadb.net/Artist/Edit/14798' - System.Threading.ThreadAbortException 
Thread was being aborted. Int32 MgdReadEntityBody(IntPtr, Byte[], Int32, Int32, 
Boolean, Int32 ByRef, IntPtr ByRef)    at 
System.Web.Hosting.UnsafeIISMethods.MgdReadEntityBody(IntPtr pHandler, Byte[] 
pBuffer, Int32 dwOffset, Int32 dwBytesToRead, Boolean fAsync, Int32& 
pBytesRead, IntPtr& ppAsyncReceiveBuffer)
   at System.Web.Hosting.IIS7WorkerRequest.ReadEntityCoreSync(Byte[] buffer, Int32 offset, Int32 size)
   at System.Web.HttpRequest.GetEntireRawContent()
   at System.Web.HttpRequest.GetMultipartContent()
   at System.Web.HttpRequest.FillInFormCollection()
   at System.Web.HttpRequest.EnsureForm()
   at System.Web.HttpRequest.get_Form()
   at VocaDb.Web.MvcApplication.IsAjaxRequest(HttpRequest request) in c:\Sites\VocaDB\trunk\VocaDbWeb\Global.asax.cs:line 36
   at VocaDb.Web.MvcApplication.Application_AuthenticateRequest(Object sender, EventArgs e) in c:\Sites\VocaDB\trunk\VocaDbWeb\Global.asax.cs:line 70

2013-09-26 18:51:55.2717 [] ERROR Exception for 'IP' [IP], URL POST 
'/Artist/EditBasicDetails', UA 'Chrome', referrer 
'http://vocadb.net/Artist/Edit/14798' - System.Web.HttpException Request timed 
out. 

It seems this has something to do with multi-part forms. These are used for 
uploading pictures. Not sure if it's caused by the user's browser or the 
server. Might just be a slow connection as well, in which case increasing the 
request timeout (currently the default, 110 seconds) would help.
```

Original issue reported on code.google.com by `rii...@gmail.com` on 26 Sep 2013 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
Likely solved. Caused by user double-clicking the save button. Corrected by 
disabling the save button while submitting.
```

Original comment by `rii...@gmail.com` on 3 Oct 2013 at 6:41
- Changed state: **Done**
